import { NextRequest, NextResponse } from 'next/server';

import { bearerFromHeader, verifyAuthToken } from '@/lib/auth/tokens';
import {
  findPairingBySession,
  findPhoneReport,
  upsertPhoneReport,
} from '@/lib/auth/store';

/**
 * POST /api/phone/report
 *
 * Receives the on-device distraction report generated by the iOS companion's
 * embedded Zetic Melange LLM (`Steve/Qwen3.5-2B` running on Apple Neural
 * Engine via `ZeticMLangeLLMModel`). The text + per-category counters travel
 * over the wire so the desktop can render them, but the analysis itself runs
 * **entirely on the phone**.
 *
 * GET /api/phone/report?sessionId=... returns the latest report for the
 * session, used by the desktop to render the report panel.
 */
export async function POST(req: NextRequest) {
  const token = bearerFromHeader(req.headers.get('authorization'));
  const payload = verifyAuthToken(token);
  if (!payload) {
    return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });
  }

  const body = (await req.json()) as {
    sessionId?: string;
    summary?: string;
    perCategoryMinutes?: Record<string, number>;
    modelKey?: string;
    inferenceMs?: number;
    promptTokens?: number;
    completionTokens?: number;
  };

  const { sessionId, summary } = body;
  if (!sessionId || !summary) {
    return NextResponse.json(
      { error: 'sessionId and summary required' },
      { status: 400 },
    );
  }

  const pairing = await findPairingBySession(sessionId);
  if (!pairing) {
    return NextResponse.json({ error: 'session not paired' }, { status: 404 });
  }
  if (pairing.userId !== payload.uid) {
    return NextResponse.json(
      { error: 'session belongs to a different account' },
      { status: 403 },
    );
  }

  await upsertPhoneReport({
    sessionId,
    userId: payload.uid,
    summary,
    perCategoryMinutes: body.perCategoryMinutes ?? {},
    modelKey: body.modelKey ?? 'Steve/Qwen3.5-2B',
    inferenceMs: body.inferenceMs ?? 0,
    promptTokens: body.promptTokens ?? 0,
    completionTokens: body.completionTokens ?? 0,
    createdAt: Date.now(),
  });

  return NextResponse.json({ status: 'ok' });
}

export async function GET(req: NextRequest) {
  const token = bearerFromHeader(req.headers.get('authorization'));
  const payload = verifyAuthToken(token);
  if (!payload) {
    return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });
  }
  const sessionId = req.nextUrl.searchParams.get('sessionId');
  if (!sessionId) {
    return NextResponse.json({ error: 'sessionId required' }, { status: 400 });
  }
  const report = await findPhoneReport(sessionId);
  if (!report) {
    return NextResponse.json({ report: null });
  }
  if (report.userId !== payload.uid) {
    return NextResponse.json(
      { error: 'session belongs to a different account' },
      { status: 403 },
    );
  }
  return NextResponse.json({ report });
}
